Repository RosettaCommons/rosetta, pull requests merged in 2024-04, with the labels that each got.

#40 Fix uninitialized variable in InterfaceScoreCalculator
  source/src/protocols/ligand_docking/InterfaceScoreCalculator.hh
Labels: ready_for_review, 90 standard tests

#43 rename torch extras and defines
  source/src/protocols/inverse_folding/MIFST.cc
  source/src/protocols/inverse_folding/MIFST.hh
  source/src/protocols/inverse_folding/MIFSTProbabilitiesMetric.cc
  source/src/protocols/inverse_folding/util.cc
  source/src/protocols/inverse_folding/util.hh
  source/src/protocols/protein_mpnn/ProteinMPNN.cc
  source/src/protocols/protein_mpnn/ProteinMPNN.hh
  source/src/protocols/protein_mpnn/ProteinMPNNMover.cc
  source/src/protocols/protein_mpnn/ProteinMPNNProbabilitiesMetric.cc
  source/src/protocols/protein_mpnn/ProteinMPNNProbabilitiesMetric.hh
  source/src/protocols/protein_mpnn/util.cc
  source/src/protocols/protein_mpnn/util.hh
  source/src/python/PyRosetta/build.py
  source/tools/build/basic.settings
  tests/benchmark/tests/integration.py
Labels: 40 machine learning, 00 build

#26 QOL update to the PerResidueEsmProbabilitiesMetric
  database/citations/rosetta_citations.txt
  source/src/protocols/esm_perplexity/EsmPerplexityTensorflowProtocol.cc
  source/src/protocols/esm_perplexity/EsmPerplexityTensorflowProtocol.hh
  source/src/protocols/esm_perplexity/PerResidueEsmProbabilitiesMetric.cc
  source/src/protocols/esm_perplexity/PseudoPerplexityMetric.cc
  source/src/protocols/inverse_folding/MIFST.cc
  source/src/protocols/inverse_folding/MIFST.hh
  source/src/protocols/simple_moves/SampleSequenceFromProbabilities.cc
  source/src/protocols/simple_moves/SampleSequenceFromProbabilities.hh
Labels: ready_for_review, 40 machine learning, 90 standard tests

#38 cifparse: Debian missing unistd include
  source/external/cifparse/CifScanner.c
  source/external/cifparse/DICScanner.c
Labels: 01 unit

#36 Add ability to specify compiler version ranges in scons settings.
  source/src/protocols/ligand_docking/GALigandDock/LigandAligner.cc
  source/src/utility/tag/Tag.cc
  source/tools/build/basic.settings
  source/tools/build/setup.py
Labels: 00 build

#50 Update benchmark.py, add how-to-fix explanation to warning message
  tests/benchmark/benchmark.py
Labels: 02 integration

#51 Update benchmark scripts for Python3.12.
  source/version.py
  tests/benchmark/benchmark.py
  tests/benchmark/tests/PyRosetta.py
  tests/benchmark/tests/__init__.py
  tests/benchmark/tests/build.py
  tests/benchmark/tests/code_quality.py
  tests/benchmark/tests/integration.py
  tests/benchmark/tests/maintenance.py
  tests/benchmark/tests/performance.py
  tests/benchmark/tests/profile.py
  tests/benchmark/tests/release.py
  tests/benchmark/tests/scientific/_dir_template_/command.py
  tests/benchmark/tests/scientific/_template_test_suite_.py
  tests/benchmark/tests/scientific/command.py
  tests/benchmark/tests/scientific/protein_data_bank_diagnostic/command.py
  tests/benchmark/tests/score.py
  tests/benchmark/tests/scripts.py
  tests/benchmark/tests/self.py
  tests/benchmark/tests/unit.py
  tests/benchmark/tests/util.py
  tests/benchmark/tests/windows.py
Labels: ready_for_review, 99 master tests, 90 standard tests, 91 release
