Repository RosettaCommons/rosetta, pull requests merged in 2025-07, with the labels that each got.

#313 Add header for INT_MAX
  source/src/protocols/toolbox/NetworkAlgorithms.cc
Labels: ready_for_review, 90 standard tests

#263 Lanthipeptide and recon multistate design update
  database/chemical/residue_type_sets/fa_standard/patches/Nterm2_Oxobutrylation.txt
  source/src/core/scoring/constraints/ResidueTypeConstraint.cc
  source/src/core/scoring/constraints/ResidueTypeConstraint.hh
  source/src/protocols/cyclic_peptide/crosslinker/lanthionine_util.cc
  source/src/protocols/cyclic_peptide/crosslinker/lanthionine_util.hh
  source/src/protocols/cyclic_peptide_predict/SimpleCycpepPredictApplication.cc
  source/src/protocols/recon_design/FindConsensusSequence.cc
  source/src/protocols/recon_design/MSDMover.cc
  source/src/protocols/recon_design/MSDMover.hh
  source/src/protocols/recon_design/recon_util.cc
  source/src/protocols/recon_design/recon_util.hh
  source/test/protocols/recon_design/MSDMoverTest.cxxtest.hh
Labels: 90 standard tests

#349 FakeRotLib and minor tweaks to m2pp.py
  source/scripts/python/public/fake_rotlib.py
  source/scripts/python/public/molfile_to_params_polymer/IO_functions.py
  source/scripts/python/public/molfile_to_params_polymer/atom_functions.py
Labels: ready_for_review, 90 standard tests

#372 Add option to control intermediate dumping in BackrubProtocol
  source/src/protocols/backrub/BackrubProtocol.cc
  source/src/protocols/backrub/BackrubProtocol.hh
Labels: ready_for_review, 90 standard tests

#457 Add cartesian option to RosettaLigand FinalMinimizer.
  source/src/protocols/ligand_docking/FinalMinimizer.cc
  source/src/protocols/ligand_docking/FinalMinimizer.hh
Labels: ready_for_review, 90 standard tests

#456 Add RosettaLigand docking scores to the Pose when JD2 is not active.
  source/src/protocols/ligand_docking/InterfaceScoreCalculator.cc
  source/src/protocols/ligand_docking/LigandDockingLoaders.cc
  source/src/protocols/ligand_docking/Transform.cc
  source/src/protocols/ligand_docking/util.cc
  source/src/protocols/ligand_docking/util.hh
  tests/integration/tests/ligand_dock_script_jd3/command
  tests/integration/tests/ligand_dock_script_jd3/flags
  tests/integration/tests/ligand_dock_script_jd3/inputs/7cpa.params
  tests/integration/tests/ligand_dock_script_jd3/inputs/7cpa_confs.pdb
  tests/integration/tests/ligand_dock_script_jd3/inputs/7cpa_confs.pdb.gz
  tests/integration/tests/ligand_dock_script_jd3/inputs/7cpa_input.pdb.gz
  tests/integration/tests/ligand_dock_script_jd3/inputs/7cpa_native.pdb.gz
  tests/integration/tests/ligand_dock_script_jd3/inputs/ZNx.params
  tests/integration/tests/ligand_dock_script_jd3/ligand_dock.xml
Labels: ready_for_review, 90 standard tests

#452 Support yielding PackedPose objects in memory from PyRosettaCluster
  source/src/python/PyRosetta/src/pyrosetta/distributed/cluster/__init__.py
  source/src/python/PyRosetta/src/pyrosetta/distributed/cluster/converters.py
  source/src/python/PyRosetta/src/pyrosetta/distributed/cluster/core.py
  source/src/python/PyRosetta/src/pyrosetta/distributed/cluster/toolkit.py
  source/src/python/PyRosetta/src/pyrosetta/distributed/cluster/tools.py
  source/src/python/PyRosetta/src/pyrosetta/tests/distributed/cluster/test_reproducibility.py
  source/src/python/PyRosetta/src/pyrosetta/tests/distributed/cluster/test_smoke.py
Labels: enhancement, 03 PyRosetta, industry

#483 Fix parse_options arguments with local OptionsCollection in ProtocolSettingsMetric.cc
  source/src/core/simple_metrics/composite_metrics/ProtocolSettingsMetric.cc
Labels: bug, ready_for_review, 90 standard tests, industry

#484 Set correct scope for automatic protocol detection in PyRosettaCluster reproduction
  source/src/python/PyRosetta/src/pyrosetta/distributed/cluster/tools.py
  source/src/python/PyRosetta/src/pyrosetta/tests/distributed/cluster/test_reproducibility.py
Labels: bug, ready_for_review, 03 PyRosetta, industry
